# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: v1
kind: Service
metadata:
  name: server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: soft-serve.ajphome.com.
