apiVersion: v1
kind: PersistentVolume
metadata:
  name: soft-serve-server
spec:
  volumeMode: Filesystem
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /srv/soft-serve
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: soft-serve
    name: soft-serve-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - core
