apiVersion: v1
kind: PersistentVolume
metadata:
  name: meshcentral-web
spec:
  volumeMode: Filesystem
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /srv/meshcentral/web/data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: meshcentral
    name: meshcentral-web
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - core
