# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: v1
kind: Service
metadata:
  name: image-automation-controller
  namespace: flux-system
spec:
  selector:
    app: image-automation-controller
  ports:
  - name: http-prom
    port: 8080
    protocol: TCP
    targetPort: http-prom
