apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: infra
spec:
  k0s:
    config:
      spec:
        extensions:
          helm:
            repositories:
            - name: metallb
              url: https://metallb.github.io/metallb
            - name: fluxcd-community
              url: https://fluxcd-community.github.io/helm-charts
            charts:
            - name: metallb
              chartname: metallb/metallb
              namespace: metallb-system
              order: 1
            - name: flux2
              chartname: fluxcd-community/flux2
              order: 2
              version: "2.12.4"
              namespace: flux-system
