# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: monitoring
spec:
  secretName: prometheus-tls
  issuerRef:
    name: ca
    kind: ClusterIssuer
  commonName: prometheus.ajphome.com
  dnsNames:
  - prometheus.ajphome.com
