apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: web
  newName: ghcr.io/ylianst/meshcentral
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: web
configMapGenerator:
- name: web
  files:
  - config.json
resources:
- deployment.yaml
- service.yaml
- pvc.yaml
