# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
