# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: https
  - name: bio
    port: 4433
    targetPort: bio
