apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-tls
spec:
  commonName: soft-serve.ajphome.com
  secretName: server-tls
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: ca
    kind: ClusterIssuer
    group: cert-manager.io
