apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: server
  newName:  ghcr.io/charmbracelet/soft-serve
  newTag: v0.7.4
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: server
configMapGenerator:
- name: server
  files:
  - config.yaml
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
