apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
  - name: http
    port: 80
    targetPort: http
  - name: stats
    port: 8080
    targetPort: stats
  - name: git-daemon
    port: 9418
    targetPort: git-daemon
