# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tftp
spec:
  selector:
  template:
    spec:
      containers:
      - name: tftp
        image: tftp
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - name: tftp
          protocol: UDP
          containerPort: 69
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
      securityContext:
        seccompProfile:
          type: RuntimeDefault
