apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: tftp
  newName: dockurr/dnsmasq
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: tftp
configMapGenerator:
- name: tftp
  files:
  - dnsmasq.conf
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
