# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: v1
kind: Service
metadata:
  name: tftp
spec:
  type: LoadBalancer
  ports:
  - name: tftp
    port: 69
    protocol: UDP
    targetPort: tftp
