# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
- namespace.patch.yaml
- default.IPAddressPool.yaml
- default.L2Advertisement.yaml
