apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
- namespace.yaml
- default.IPAddressPool.yaml
- default.L2Advertisement.yaml
- metallb.helmrelease.yaml
