# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: directpv
spec:
  interval: 5m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: directpv
  path: ./resources/base
  targetNamespace: directpv
  patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
        value: "true"
    target:
      kind: StorageClass
      name: directpv-min-io
