apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dns
spec:
  interval: 5m0s
  path: ./dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: core-data
  targetNamespace: external-dns
