# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: docker-registry
spec:
  targetNamespace: docker-registry
  install:
    createNamespace: true
  interval: 10m
  chart:
    spec:
      chart: docker-registry
      version: "1.10.*"
      sourceRef:
        kind: HelmRepository
        name: phntom
  values:
    tlsSecretName: docker-registry-tls
    persistence:
      enabled: true
      size: 10Gi
      storageClass: openebs-hostpath
    service:
      type: LoadBalancer
      port: 5000
      annotations:
        external-dns.alpha.kubernetes.io/hostname: registry.ajphome.com
        metallb.universe.tf/loadBalancerIPs: 10.0.0.205
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
