apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  targetNamespace: external-dns
  install:
    createNamespace: true
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "v7.5.*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    provider: webhook
    registry: noop
    extraArgs:
      webhook-provider-url: http://localhost:8800
    managedRecordTypesFilters:
    - A
    - AAAA
    sources:
    - pod
    - service
    sidecars:
    - name: opnsense-unbound-external-dns-webhook
      image: ghcr.io/jobs62/opnsense_unbound_external-dns_webhook:v0.2.0-rc1
      ports:
      - containerPort: 8800
        name: http
      env:
      - name: OPNSENSE_BASE
        valueFrom:
          configMapKeyRef:
            name: opnsense
            key: base
      - name: OPNSENSE_ALLOW_INVALID_CERTS
        value: "true"
      - name: OPNSENSE_DOMAIN_FILTERS
        value: "[\".ajphome.com\"]"
      - name: OPNSENSE_KEY
        valueFrom:
          secretKeyRef:
            name: opnsense
            key: key
      - name: OPNSENSE_SECRET
        valueFrom:
          secretKeyRef:
            name: opnsense
            key: secret
