# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
spec:
  interval: 10m0s
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-core
  dependsOn:
  - name: prometheus
  targetNamespace: flux-system
