apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: haproxy
spec:
  targetNamespace: haproxy
  install:
    createNamespace: true
  chart:
    spec:
      chart: haproxy
      version: 1.22.*
      sourceRef:
        kind: HelmRepository
        name: haproxytech
  interval: 10m0s
  values:
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: homelab.ajphome.com.
    containerPorts:
      api: 6443
      konnectivity: 8132
      join: 9443
    config: |
      global
        log stdout format raw local0
        daemon
        maxconn 1024
      defaults
        log global
        timeout client 60s
        timeout connect 60s
        timeout server 60s
      resolvers ajphome.com
        nameserver ns1 10.0.0.1:53
      frontend kubeAPI
          bind :6443
          mode tcp
          default_backend kubeAPI_backend
      frontend konnectivity
          bind :8132
          mode tcp
          default_backend konnectivity_backend
      frontend controllerJoinAPI
          bind :9443
          mode tcp
          default_backend controllerJoinAPI_backend
      backend kubeAPI_backend
          mode tcp
          server k0s-controller1 lab-001.ajphome.com:6443 check check-ssl verify none resolvers ajphome.com
          server k0s-controller2 lab-002.ajphome.com:6443 check check-ssl verify none resolvers ajphome.com
          server k0s-controller3 lab-003.ajphome.com:6443 check check-ssl verify none resolvers ajphome.com
      backend konnectivity_backend
          mode tcp
          server k0s-controller1 lab-001.ajphome.com:8132 check check-ssl verify none resolvers ajphome.com
          server k0s-controller2 lab-002.ajphome.com:8132 check check-ssl verify none resolvers ajphome.com
          server k0s-controller3 lab-003.ajphome.com:8132 check check-ssl verify none resolvers ajphome.com
      backend controllerJoinAPI_backend
          mode tcp
          server k0s-controller1 lab-001.ajphome.com:9443 check check-ssl verify none resolvers ajphome.com
          server k0s-controller2 lab-002.ajphome.com:9443 check check-ssl verify none resolvers ajphome.com
          server k0s-controller3 lab-003.ajphome.com:9443 check check-ssl verify none resolvers ajphome.com
      listen stats
        bind *:9000
        mode http
        stats enable
        stats uri /
