apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metallb
spec:
  targetNamespace: metallb-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metalllb
  interval: 10m
