apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
spec:
  interval: 5m0s
  path: ./metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  targetNamespace: metallb-system
