# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: phntom
spec:
  interval: 24h0m0s
  url: https://phntom.kix.co.il/charts/
