# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: project-zot
spec:
  interval: 24h0m0s
  url: http://zotregistry.dev/helm-charts
