# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
spec:
  interval: 10m0s
  path: ./prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-core
  dependsOn:
  - name: cert-manager
