# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
  template:
    metadata:
    spec:
      containers:
      - name: web
        image: web
        command:
        - "nginx"
        - "-g"
        - "daemon off;"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        seccompProfile:
          type: RuntimeDefault
