apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
  template:
    metadata:
    spec:
      nodeSelector:
        kubernetes.io/hostname: pxe
      containers:
      - name: web
        image: web
        command:
        - "nginx"
        - "-g"
        - "daemon off;"
        volumeMounts:
        - name: data
          mountPath: /opt/app-root/src
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: web
