# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: web
  newName: registry.ajphome.com:5000/pxe-http
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: web
resources:
- deployment.yaml
- service.yaml
