apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: web
  newName: registry.access.redhat.com/ubi9/nginx-122
  newTag: 1-69.1714669800
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: web
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
