# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: web
  newName: registry.access.redhat.com/ubi9/nginx-126
  newTag: 1-1756959223
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: web
resources:
- deployment.yaml
- service.yaml
- persistentvolumeclaim.yaml
