# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-dns
  labels:
    release: monitoring-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  namespaceSelector:
    matchNames:
    - external-dns
  endpoints:
  - port: http
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics
