apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root
spec:
  isCA: true
  commonName: cluster-ca
  secretName: ca-root
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: ca-bootstrap
    kind: ClusterIssuer
    group: cert-manager.io
