# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ca-bootstrap.ClusterIssuer.yaml
- ./ca-root.Certificate.yaml
- ./ca.ClusterIssuer.yaml
