apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pxe
resources:
- ../../base
- ./namespace.yaml
- ./pxe-tftp.persistentvolume.yaml
- ./pxe-web.persistentvolume.yaml
- ./storageclass.yaml
patches:
- path: ./service.patch.yaml
