# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: v1
kind: Service
metadata:
  name: web
  annotations:
    metallb.universe.tf/allow-shared-ip: "pxe"
    external-dns.alpha.kubernetes.io/hostname: pxe.ajphome.com.
